# Generated by Django 3.0.3 on 2020-02-23 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('elimination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='initial_password',
            field=models.CharField(default='AAAAA', max_length=5,
                                   validators=[django.core.validators.RegexValidator('^[A-Z]{5}$')]),
            preserve_default=False,
        ),
    ]
