# Generated by Django 3.0.3 on 2020-02-25 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('elimination', '0002_senior_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='elimination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
