# Generated by Django 3.0.3 on 2020-02-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('elimination', '0003_elimination_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminationNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimination.Elimination')),
            ],
        ),
    ]
